# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ostorlab-azure-security-scanner@1
  inputs:
    apiKey: 'qLKQhdAK.QyxmzLneYrBKo4IfPLQxHWzzDkIVjehx'
    filepath: '$(Build.SourcesDirectory)/test.apk'
    platform: 'android'
    artifactsDir: '$(build.artifactStagingDirectory)/ostorlabArtifacts'
    scanProfile: 'Fast Scan'
    title: 'Scan_title_azure'
    waitMinutes: 0
    extra: |      
      sbom:          
        - '$(Build.SourcesDirectory)/package_lock.json'
  env:
    OSTORLABSCANID: $(OstorlabScanId)
- bash: echo $(OSTORLABSCANID)
  displayName: 'ENV var'
