name: Build and Release APK
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Prepare NDK dir for caching ( workaround for https://github.com/actions/virtual-environments/issues/1337 )
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/ndk
          sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk

      - name: install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: 'stable'

      - name: Get dependencies
        working-directory: ostorlab_insecure_flutter_app
        run: flutter pub get

      - name: Start AAR build
        working-directory: ostorlab_insecure_flutter_app
        run: flutter build aar --no-sound-null-safety

      - name: Build Android app
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembleRelease
          gradle-version: 7.3.3

      - name: Install Uber APK Signer
        run: |
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Sign APK
        run: |
          java -jar uber-apk-signer-1.3.0.jar --apks ./app/build/outputs/apk/release/app-release-unsigned.apk -o ostorlab_insecure_app

      - name: Move to release
        run: |
          cp ./ostorlab_insecure_app/app-release-aligned-debugSigned.apk ostorlab_insecure_app.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./ostorlab_insecure_app.apk
